/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ResumeId = IDL.Nat;
export const AnalysisId = IDL.Nat;
export const AnalysisSuggestion = IDL.Record({
  'suggestion' : IDL.Text,
  'category' : IDL.Text,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const SkillEntry = IDL.Record({
  'level' : IDL.Text,
  'skill' : IDL.Text,
});
export const ResumeAnalysis = IDL.Record({
  'id' : AnalysisId,
  'suggestions' : IDL.Vec(AnalysisSuggestion),
  'owner' : UserId,
  'gaps' : IDL.Vec(IDL.Text),
  'summary' : IDL.Text,
  'resumeId' : ResumeId,
  'atsScore' : IDL.Nat,
  'analyzedAt' : Timestamp,
  'skills' : IDL.Vec(SkillEntry),
});
export const UserProfilePublic = IDL.Record({
  'id' : UserId,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'careerFocus' : IDL.Text,
});
export const MatchId = IDL.Nat;
export const SkillMatch = IDL.Record({
  'skill' : IDL.Text,
  'matched' : IDL.Bool,
  'relevance' : IDL.Nat,
});
export const JobMatchPublic = IDL.Record({
  'id' : MatchId,
  'matchedAt' : Timestamp,
  'isSaved' : IDL.Bool,
  'coverLetterDraft' : IDL.Text,
  'owner' : UserId,
  'description' : IDL.Text,
  'relevanceScore' : IDL.Nat,
  'redFlags' : IDL.Vec(IDL.Text),
  'resumeId' : ResumeId,
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'location' : IDL.Text,
  'skillBreakdown' : IDL.Vec(SkillMatch),
});
export const DashboardStats = IDL.Record({
  'totalAnalyses' : IDL.Nat,
  'totalResumes' : IDL.Nat,
  'totalMatches' : IDL.Nat,
  'latestAtsScore' : IDL.Opt(IDL.Nat),
  'avgMatchScore' : IDL.Nat,
});
export const ResumePublic = IDL.Record({
  'id' : ResumeId,
  'tag' : IDL.Text,
  'owner' : UserId,
  'isActive' : IDL.Bool,
  'filename' : IDL.Text,
  'uploadedAt' : Timestamp,
  'fileKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  'analyzeResume' : IDL.Func([ResumeId], [ResumeAnalysis], []),
  'createProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfilePublic], []),
  'deleteResume' : IDL.Func([ResumeId], [IDL.Bool], []),
  'findJobMatches' : IDL.Func([ResumeId], [IDL.Vec(JobMatchPublic)], []),
  'getAnalysisHistory' : IDL.Func([], [IDL.Vec(ResumeAnalysis)], ['query']),
  'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
  'getJobMatches' : IDL.Func([], [IDL.Vec(JobMatchPublic)], ['query']),
  'getLatestAnalysis' : IDL.Func(
      [ResumeId],
      [IDL.Opt(ResumeAnalysis)],
      ['query'],
    ),
  'getMatchDetail' : IDL.Func([MatchId], [IDL.Opt(JobMatchPublic)], ['query']),
  'getProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
  'listResumes' : IDL.Func([], [IDL.Vec(ResumePublic)], ['query']),
  'removeJobMatch' : IDL.Func([MatchId], [IDL.Bool], []),
  'saveJobMatch' : IDL.Func([MatchId], [IDL.Bool], []),
  'setActiveResume' : IDL.Func([ResumeId], [IDL.Bool], []),
  'transformAnalysis' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'transformJobs' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfilePublic], []),
  'uploadResume' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [ResumePublic], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ResumeId = IDL.Nat;
  const AnalysisId = IDL.Nat;
  const AnalysisSuggestion = IDL.Record({
    'suggestion' : IDL.Text,
    'category' : IDL.Text,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const SkillEntry = IDL.Record({ 'level' : IDL.Text, 'skill' : IDL.Text });
  const ResumeAnalysis = IDL.Record({
    'id' : AnalysisId,
    'suggestions' : IDL.Vec(AnalysisSuggestion),
    'owner' : UserId,
    'gaps' : IDL.Vec(IDL.Text),
    'summary' : IDL.Text,
    'resumeId' : ResumeId,
    'atsScore' : IDL.Nat,
    'analyzedAt' : Timestamp,
    'skills' : IDL.Vec(SkillEntry),
  });
  const UserProfilePublic = IDL.Record({
    'id' : UserId,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'careerFocus' : IDL.Text,
  });
  const MatchId = IDL.Nat;
  const SkillMatch = IDL.Record({
    'skill' : IDL.Text,
    'matched' : IDL.Bool,
    'relevance' : IDL.Nat,
  });
  const JobMatchPublic = IDL.Record({
    'id' : MatchId,
    'matchedAt' : Timestamp,
    'isSaved' : IDL.Bool,
    'coverLetterDraft' : IDL.Text,
    'owner' : UserId,
    'description' : IDL.Text,
    'relevanceScore' : IDL.Nat,
    'redFlags' : IDL.Vec(IDL.Text),
    'resumeId' : ResumeId,
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'location' : IDL.Text,
    'skillBreakdown' : IDL.Vec(SkillMatch),
  });
  const DashboardStats = IDL.Record({
    'totalAnalyses' : IDL.Nat,
    'totalResumes' : IDL.Nat,
    'totalMatches' : IDL.Nat,
    'latestAtsScore' : IDL.Opt(IDL.Nat),
    'avgMatchScore' : IDL.Nat,
  });
  const ResumePublic = IDL.Record({
    'id' : ResumeId,
    'tag' : IDL.Text,
    'owner' : UserId,
    'isActive' : IDL.Bool,
    'filename' : IDL.Text,
    'uploadedAt' : Timestamp,
    'fileKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    'analyzeResume' : IDL.Func([ResumeId], [ResumeAnalysis], []),
    'createProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfilePublic], []),
    'deleteResume' : IDL.Func([ResumeId], [IDL.Bool], []),
    'findJobMatches' : IDL.Func([ResumeId], [IDL.Vec(JobMatchPublic)], []),
    'getAnalysisHistory' : IDL.Func([], [IDL.Vec(ResumeAnalysis)], ['query']),
    'getDashboardStats' : IDL.Func([], [DashboardStats], ['query']),
    'getJobMatches' : IDL.Func([], [IDL.Vec(JobMatchPublic)], ['query']),
    'getLatestAnalysis' : IDL.Func(
        [ResumeId],
        [IDL.Opt(ResumeAnalysis)],
        ['query'],
      ),
    'getMatchDetail' : IDL.Func(
        [MatchId],
        [IDL.Opt(JobMatchPublic)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [IDL.Opt(UserProfilePublic)], ['query']),
    'listResumes' : IDL.Func([], [IDL.Vec(ResumePublic)], ['query']),
    'removeJobMatch' : IDL.Func([MatchId], [IDL.Bool], []),
    'saveJobMatch' : IDL.Func([MatchId], [IDL.Bool], []),
    'setActiveResume' : IDL.Func([ResumeId], [IDL.Bool], []),
    'transformAnalysis' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'transformJobs' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateProfile' : IDL.Func([IDL.Text, IDL.Text], [UserProfilePublic], []),
    'uploadResume' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [ResumePublic],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };