/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type AnalysisId = bigint;
export interface AnalysisSuggestion {
  'suggestion' : string,
  'category' : string,
}
export interface DashboardStats {
  'totalAnalyses' : bigint,
  'totalResumes' : bigint,
  'totalMatches' : bigint,
  'latestAtsScore' : [] | [bigint],
  'avgMatchScore' : bigint,
}
export interface JobMatchPublic {
  'id' : MatchId,
  'matchedAt' : Timestamp,
  'isSaved' : boolean,
  'coverLetterDraft' : string,
  'owner' : UserId,
  'description' : string,
  'relevanceScore' : bigint,
  'redFlags' : Array<string>,
  'resumeId' : ResumeId,
  'company' : string,
  'jobTitle' : string,
  'location' : string,
  'skillBreakdown' : Array<SkillMatch>,
}
export type MatchId = bigint;
export interface ResumeAnalysis {
  'id' : AnalysisId,
  'suggestions' : Array<AnalysisSuggestion>,
  'owner' : UserId,
  'gaps' : Array<string>,
  'summary' : string,
  'resumeId' : ResumeId,
  'atsScore' : bigint,
  'analyzedAt' : Timestamp,
  'skills' : Array<SkillEntry>,
}
export type ResumeId = bigint;
export interface ResumePublic {
  'id' : ResumeId,
  'tag' : string,
  'owner' : UserId,
  'isActive' : boolean,
  'filename' : string,
  'uploadedAt' : Timestamp,
  'fileKey' : string,
}
export interface SkillEntry { 'level' : string, 'skill' : string }
export interface SkillMatch {
  'skill' : string,
  'matched' : boolean,
  'relevance' : bigint,
}
export type Timestamp = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export type UserId = Principal;
export interface UserProfilePublic {
  'id' : UserId,
  'name' : string,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'careerFocus' : string,
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  'analyzeResume' : ActorMethod<[ResumeId], ResumeAnalysis>,
  'createProfile' : ActorMethod<[string, string], UserProfilePublic>,
  'deleteResume' : ActorMethod<[ResumeId], boolean>,
  'findJobMatches' : ActorMethod<[ResumeId], Array<JobMatchPublic>>,
  'getAnalysisHistory' : ActorMethod<[], Array<ResumeAnalysis>>,
  'getDashboardStats' : ActorMethod<[], DashboardStats>,
  'getJobMatches' : ActorMethod<[], Array<JobMatchPublic>>,
  'getLatestAnalysis' : ActorMethod<[ResumeId], [] | [ResumeAnalysis]>,
  'getMatchDetail' : ActorMethod<[MatchId], [] | [JobMatchPublic]>,
  'getProfile' : ActorMethod<[], [] | [UserProfilePublic]>,
  'listResumes' : ActorMethod<[], Array<ResumePublic>>,
  'removeJobMatch' : ActorMethod<[MatchId], boolean>,
  'saveJobMatch' : ActorMethod<[MatchId], boolean>,
  'setActiveResume' : ActorMethod<[ResumeId], boolean>,
  'transformAnalysis' : ActorMethod<
    [TransformationInput],
    TransformationOutput
  >,
  'transformJobs' : ActorMethod<[TransformationInput], TransformationOutput>,
  'updateProfile' : ActorMethod<[string, string], UserProfilePublic>,
  'uploadResume' : ActorMethod<[string, string, string], ResumePublic>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];