/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface SkillMatch {
    skill: string;
    matched: boolean;
    relevance: bigint;
}
export type Timestamp = bigint;
export interface TransformationOutput {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface SkillEntry {
    level: string;
    skill: string;
}
export type MatchId = bigint;
export interface http_header {
    value: string;
    name: string;
}
export interface ResumePublic {
    id: ResumeId;
    tag: string;
    owner: UserId;
    isActive: boolean;
    filename: string;
    uploadedAt: Timestamp;
    fileKey: string;
}
export type ResumeId = bigint;
export type UserId = Principal;
export interface UserProfilePublic {
    id: UserId;
    name: string;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    careerFocus: string;
}
export interface JobMatchPublic {
    id: MatchId;
    matchedAt: Timestamp;
    isSaved: boolean;
    coverLetterDraft: string;
    owner: UserId;
    description: string;
    relevanceScore: bigint;
    redFlags: Array<string>;
    resumeId: ResumeId;
    company: string;
    jobTitle: string;
    location: string;
    skillBreakdown: Array<SkillMatch>;
}
export interface ResumeAnalysis {
    id: AnalysisId;
    suggestions: Array<AnalysisSuggestion>;
    owner: UserId;
    gaps: Array<string>;
    summary: string;
    resumeId: ResumeId;
    atsScore: bigint;
    analyzedAt: Timestamp;
    skills: Array<SkillEntry>;
}
export interface http_request_result {
    status: bigint;
    body: Uint8Array;
    headers: Array<http_header>;
}
export interface TransformationInput {
    context: Uint8Array;
    response: http_request_result;
}
export interface DashboardStats {
    totalAnalyses: bigint;
    totalResumes: bigint;
    totalMatches: bigint;
    latestAtsScore?: bigint;
    avgMatchScore: bigint;
}
export interface AnalysisSuggestion {
    suggestion: string;
    category: string;
}
export type AnalysisId = bigint;
export interface backendInterface {
    analyzeResume(resumeId: ResumeId): Promise<ResumeAnalysis>;
    createProfile(name: string, careerFocus: string): Promise<UserProfilePublic>;
    deleteResume(resumeId: ResumeId): Promise<boolean>;
    findJobMatches(resumeId: ResumeId): Promise<Array<JobMatchPublic>>;
    getAnalysisHistory(): Promise<Array<ResumeAnalysis>>;
    getDashboardStats(): Promise<DashboardStats>;
    getJobMatches(): Promise<Array<JobMatchPublic>>;
    getLatestAnalysis(resumeId: ResumeId): Promise<ResumeAnalysis | null>;
    getMatchDetail(matchId: MatchId): Promise<JobMatchPublic | null>;
    getProfile(): Promise<UserProfilePublic | null>;
    listResumes(): Promise<Array<ResumePublic>>;
    removeJobMatch(matchId: MatchId): Promise<boolean>;
    saveJobMatch(matchId: MatchId): Promise<boolean>;
    setActiveResume(resumeId: ResumeId): Promise<boolean>;
    transformAnalysis(input: TransformationInput): Promise<TransformationOutput>;
    transformJobs(input: TransformationInput): Promise<TransformationOutput>;
    updateProfile(name: string, careerFocus: string): Promise<UserProfilePublic>;
    uploadResume(filename: string, fileKey: string, tag: string): Promise<ResumePublic>;
}
import type { DashboardStats as _DashboardStats, JobMatchPublic as _JobMatchPublic, ResumeAnalysis as _ResumeAnalysis, UserProfilePublic as _UserProfilePublic } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async analyzeResume(arg0: ResumeId): Promise<ResumeAnalysis> {
        if (this.processError) {
            try {
                const result = await this.actor.analyzeResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.analyzeResume(arg0);
            return result;
        }
    }
    async createProfile(arg0: string, arg1: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.createProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProfile(arg0, arg1);
            return result;
        }
    }
    async deleteResume(arg0: ResumeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteResume(arg0);
            return result;
        }
    }
    async findJobMatches(arg0: ResumeId): Promise<Array<JobMatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.findJobMatches(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.findJobMatches(arg0);
            return result;
        }
    }
    async getAnalysisHistory(): Promise<Array<ResumeAnalysis>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalysisHistory();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalysisHistory();
            return result;
        }
    }
    async getDashboardStats(): Promise<DashboardStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getDashboardStats();
                return from_candid_DashboardStats_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getDashboardStats();
            return from_candid_DashboardStats_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getJobMatches(): Promise<Array<JobMatchPublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.getJobMatches();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getJobMatches();
            return result;
        }
    }
    async getLatestAnalysis(arg0: ResumeId): Promise<ResumeAnalysis | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getLatestAnalysis(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLatestAnalysis(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMatchDetail(arg0: MatchId): Promise<JobMatchPublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMatchDetail(arg0);
                return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMatchDetail(arg0);
            return from_candid_opt_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfilePublic | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async listResumes(): Promise<Array<ResumePublic>> {
        if (this.processError) {
            try {
                const result = await this.actor.listResumes();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listResumes();
            return result;
        }
    }
    async removeJobMatch(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeJobMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeJobMatch(arg0);
            return result;
        }
    }
    async saveJobMatch(arg0: MatchId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveJobMatch(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveJobMatch(arg0);
            return result;
        }
    }
    async setActiveResume(arg0: ResumeId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.setActiveResume(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setActiveResume(arg0);
            return result;
        }
    }
    async transformAnalysis(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformAnalysis(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformAnalysis(arg0);
            return result;
        }
    }
    async transformJobs(arg0: TransformationInput): Promise<TransformationOutput> {
        if (this.processError) {
            try {
                const result = await this.actor.transformJobs(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.transformJobs(arg0);
            return result;
        }
    }
    async updateProfile(arg0: string, arg1: string): Promise<UserProfilePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfile(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfile(arg0, arg1);
            return result;
        }
    }
    async uploadResume(arg0: string, arg1: string, arg2: string): Promise<ResumePublic> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadResume(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadResume(arg0, arg1, arg2);
            return result;
        }
    }
}
function from_candid_DashboardStats_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DashboardStats): DashboardStats {
    return from_candid_record_n2(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ResumeAnalysis]): ResumeAnalysis | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_JobMatchPublic]): JobMatchPublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfilePublic]): UserProfilePublic | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalAnalyses: bigint;
    totalResumes: bigint;
    totalMatches: bigint;
    latestAtsScore: [] | [bigint];
    avgMatchScore: bigint;
}): {
    totalAnalyses: bigint;
    totalResumes: bigint;
    totalMatches: bigint;
    latestAtsScore?: bigint;
    avgMatchScore: bigint;
} {
    return {
        totalAnalyses: value.totalAnalyses,
        totalResumes: value.totalResumes,
        totalMatches: value.totalMatches,
        latestAtsScore: record_opt_to_undefined(from_candid_opt_n3(_uploadFile, _downloadFile, value.latestAtsScore)),
        avgMatchScore: value.avgMatchScore
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
